### ISSUE TITLE
Assess Dharma contracts for suitability / extensibility

### ISSUE THREAD

**Issue by onggunhao** [onggunhao/enable#1]
**Why**
- Dharma has a set of [open-source loan contracts](https://github.com/dharmaprotocol/charta) available 

**Todos**

- [ ] Assess suitability of Dharma contracts for multi-repayment loans with amortization schedule
- [x] Reach out to Nadav / Sid to ask about Dharma contracts / collaboration
- [ ] Install Dharma truffle box in repo (get sample loan contracts)

**Comment by tspoff** [comment]
After research, I think Dharma will be an excellent base for the loans system. We can extend the system for multi-repayment loans and have whatever kind of repayment schedule we want.

**Comment by tspoff** [comment]
**Fractional Ownership**
Loans payments are routed to the lender via ethereum address. While there is only one lender, we can have it be a smart contract that manages fractional ownership via it's own token. 

After the contract is created, lenders could contribute part of the principal to get a proportional stake of debt ownership tokens. These can then be transferred and traded like any other token. 

Lenders can claim their portion of the repayment via this contract.

**Comment by tspoff** [comment]
**amortization schedule**
We would make a custom Terms Contract to manage this.

**Comment by onggunhao** [comment]
@tspoff 

**Fractional Ownership** 
Having another contract manage fractional ownership for a Dharma loan makes a lot of sense and cuts down the surface area of logic we have to write. 

Just to get on the same page as you, the contract (referred to as `S1`) would only:

1. Manage crowdfunding process (issue fractional shares or alternative)

2. Fund Dharma loan once crowdfunding is complete, and receive Dharma Debt Token

3. Dharma Repayment Router would route repayments into smart contract

4. Smart Contract would then disburse repayment amounts to lenders based on fractional shares

**Comment by onggunhao** [comment]
Dharma contracts seem to be functional (though Dharma is no longer offering active support). I can't seem to find my documentation on the relayer, but I don't think it matters to us as we would have to take care of that anyway (since we are wrapping the existing contract)

For reference implementation, @aj07 (who is also part of this hackathon) actually worked on a Dharma contract (collateralization of ERC-721) at the ETHIndia conference.

**Comment by onggunhao** [comment]
There seems to be an NPM library (last published 10 days ago) for Dharma Contracts:
https://www.npmjs.com/package/@pstehlik/dharma-contracts

**Comment by onggunhao** [comment]
@tspoff - a few questions after going through Dharma developers:

1/ When the repayment router in Dharma sends repayments to our crowdfunding smart contract, how will our smart contract redistribute repayments to fractional owners? 

2/ Do Dharma contracts have grace periods? As borrower might need a grace period till she graduates due to family 

3/ Do Dharma contracts have early settlement terms? i.e. if she gets a high paying job, she can settle the loan in a shorter period of time (e.g. 5 years, rather than 10 years)

4/ Dharma developer program is now no longer actively supported by Dharma team - though it seems like they are mainly focused on using the contracts for their own margin-lending busines

**Comment by pstehlik** [comment]
> There seems to be a fork of Dharma.js (by @pstehlik) for Dharma Contracts:
> https://www.npmjs.com/package/@pstehlik/dharma-contracts
> 
> [Edit: Just kidding, nothing seems to have been changed]

Just toying around with some dharma.js portions to see if/how it can be used in the future with the Dharma core team not pushing forward on their implementation. Not actively developing on the fork.

**Comment by tspoff** [comment]
I'm just going to make my own loan contract for now that mimics a crowdsale. I feel like using Dharma will introduce a lot of unnecessary complexity at no (technical) benefit.

We can evaluate switching later on if we have time.

**Comment by onggunhao** [comment]
Closing this issue in favor of discussion in #65
